<a href="https://colab.research.google.com/github/yunnsss/Python/blob/main/Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
# 라이브러리 불러오기
import numpy as np

## **1. 배열 생성 및 배열 형태 변환**

### 유형1) Python의 list 혹은 tuple을 ndarray로 바꾸기

In [ ]:
# [1, 2, 3, 4, 5, 6] list를 ndarray로 바꾸기
list1 = [1, 2, 3, 4, 5, 6]
ndarray1 = np.array(list1)
print(ndarray1)

[1 2 3 4 5 6]

In [ ]:
# [1, 2, 3, 4, 5, 6] list를 ndarray로 바꾸기
## shape: 3X2인 2차원 배열
ndarray2 = np.array(list1).reshape(3, 2)
print(ndarray2)

[[1 2]
 [3 4]
 [5 6]]

### 유형2) 모두 동일한 원소로 이루어진 ndarray 생성하기

In [ ]:
# 0으로만 이루어진 ndarray
# shape: 원소가 6개인 1차원 배열
ndarray3 = np.zeros(6)
print(ndarray3)

[0. 0. 0. 0. 0. 0.]

In [ ]:
# 0으로만 이루어진 ndarray
# shape: 2X3인 2차원 배열
ndarray4 = np.zeros((2, 3))
print(ndarray4)

[[0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
# 0으로만 이루어진 ndarray
# shape: 2X3인 2차원 배열
## 데이터타입: 정수
ndarray5 = np.zeros((2, 3), dtype=int)
print(ndarray5)

[[0 0 0]
 [0 0 0]]

In [ ]:
# 1로만 이루어진 ndarray
# shape이 3X4인 2차원 배열 생성
# 데이터타입: 문자형
ndarray6 = np.ones((3, 4), dtype=str)
print(ndarray6)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]

In [ ]:
# 500으로만 이루어진 ndarray
# shape이 5X3인 2차원 배열 생성
ndarray7 = np.full((5, 3), 500)
print(ndarray7)

[[500 500 500]
 [500 500 500]
 [500 500 500]
 [500 500 500]
 [500 500 500]]

### 유형3) 연속적인 원소로 이루어진 ndarray 생성하기

In [ ]:
# 1부터 10까지 연속적인 수로 이루어진 배열
ndarray8 = np.arange(1, 11)
print(ndarray8)

[ 1  2  3  4  5  6  7  8  9 10]

In [ ]:
# 1부터 10까지 연속적인 수로 이루어진 배열
## step(공차): 2
ndarray9 = np.arange(1, 11, 2)
print(ndarray9)

[1 3 5 7 9]

In [ ]:
# 1부터 10까지 5등분한 5개의 수로 이루어진 배열
ndarray10 = np.linspace(1, 10, 5)
print(ndarray10)

[ 1.    3.25  5.5   7.75 10.  ]

### 유형4) random모듈, 주어진 배열이 존재하는 경우

In [ ]:
array = np.arange(1, 51)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

In [ ]:
# array속에서 임의로 원소 선택하여 새로운 ndarray 생성
# shape: 2X3인 2차원 배열
ndarray11 = np.random.choice(array, (2, 3))
print(ndarray11)

[[19 24 28]
 [ 1 16 34]]

In [ ]:
# array의 순서 임의로 섞기
np.random.shuffle(array)
print(array)

[41 36 28 25 33 47  6 34 17 19 43 45 31 14 20 46 15 22  5  3 13  1  4 50
  9 11 37 40 29 10 39 12 18 16 35 38 26  2  7 48 24 27 49 30 44 23 32 21
  8 42]

### 유형5) random모듈, 주어진 배열이 존재하지 않는 경우

In [ ]:
# 0이상 1미만 구간에서 난수가 균등분포 따르는 배열 생성
# shape: 5X3인 2차원 배열
ndarray12 = np.random.rand(5, 3)
print(ndarray12)

[[0.42807824 0.43233838 0.08937667]
 [0.86854279 0.34508638 0.5893031 ]
 [0.36955751 0.42421872 0.52952653]
 [0.53128037 0.80167268 0.63382329]
 [0.65548954 0.17653181 0.28238537]]

In [ ]:
# 난수가 표준정규분포 따르는 배열 생성
# shape: 5X3인 2차원 배열
ndarray13 = np.random.randn(5, 3)
print(ndarray13)

[[ 1.08306324 -0.95388135  0.44468405]
 [-0.07313041 -0.81728415  2.47894676]
 [-0.09422729  1.02178384 -0.18107033]
 [ 0.19121653  0.88572688  1.25667599]
 [-1.98047281  0.23866785 -1.19583096]]

In [ ]:
# 1부터 10까지의 정수 중 랜덤으로 수를 추출하여 배열 생성
# shape: 2X3인 2차원 배열
ndarray14 = np.random.randint(1, 11, (2, 3))
print(ndarray14)

[[2 7 7]
 [3 8 7]]

## **2. 배열 속성 확인**

In [ ]:
# 1부터 24까지 연속적인 수로 이루어진 'data'라는 배열
# shape: 2X3X4인 3차원 배열
data = np.arange(1, 25).reshape(2, 3, 4)
print(data)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

In [ ]:
# data 배열의 자료형 확인
print(data.dtype)

int64

In [ ]:
# data 배열의 차원 확인
print(data.ndim)

3

In [ ]:
# data 배열의 크기 확인
print(data.shape)

(2, 3, 4)

In [ ]:
# data 배열의 원소 개수 확인
print(data.size)

24

## **3. 배열 연산**

![Picture1.png]()

In [ ]:
# 위 사진과 같은 모양의 'array' 배열 만들기
array1 = np.array([[2.5, 1.4, 2.3],
                  [1.6, 1.2, 2.7]])
array2 = np.array([2.5, 1.4, 2.3, 1.6, 1.2, 2.7]).reshape((2, 3))

print(array1)
print(array2)

[[2.5 1.4 2.3]
 [1.6 1.2 2.7]]
[[2.5 1.4 2.3]
 [1.6 1.2 2.7]]

![output-onlinepngtools (1).png]()

In [ ]:
# array 배열의 자료형 확인
print(array1.dtype)

# array 배열의 자료형 정수로 변환
array1 = array1.astype(int) # 내림
print(array1.dtype)

float64
int64

In [ ]:
# 배열 전치
print(array1.T)

[[2 1]
 [1 1]
 [2 2]]

![Screenshot 2023-03-27 at 5.18.10 PM.png]()

### 1) 배열의 사칙연산

![Screenshot 2023-03-27 at 5.53.55 PM (1).png]()

In [ ]:
# 위 사진 모양의 'arr1'과 'arr2' 배열 생성
arr1 = np.array([[1, 2, 5, 4],
                 [4, 3, 1, 3]])
arr2 = np.arange(1, 9).reshape((2, 4))

print(arr1)
print(arr2)

[[1 2 5 4]
 [4 3 1 3]]
[[1 2 3 4]
 [5 6 7 8]]

In [ ]:
# arr1과 arr2 더하기
print(arr1 + arr2)

[[ 2  4  8  8]
 [ 9  9  8 11]]

In [ ]:
# arr1과 arr2 빼기
print(arr1 - arr2)

[[ 0  0  2  0]
 [-1 -3 -6 -5]]

In [ ]:
# arr1과 arr2 곱하기
print(arr1 * arr2)

[[ 1  4 15 16]
 [20 18  7 24]]

In [ ]:
# arr1과 arr2 나누기
print(arr1 / arr2)

[[1.         1.         1.66666667 1.        ]
 [0.8        0.5        0.14285714 0.375     ]]

In [ ]:
# arr1과 arr2.T 행렬의 곱 수행
print(arr1 @ arr2.T)

[[36 84]
 [25 69]]

+) **브로드캐스팅(broadcasting)**: 다른 형태의 배열도 연산할 수 있도록 배열의 형태를 변환하는 것
(단, 아래 3가지 경우에만 가능)
- (경우1) 하나의 배열이 원소 1개로 이루어진 배열인 경우
- (경우2) 하나의 배열이 1차원인 경우

![Screenshot 2023-03-28 at 4.20.28 PM.png]()

In [ ]:
# 경우1: 하나의 배열이 원소 1개로 이루어진 배열인 경우
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
arr2 = np.array([1])
print(arr1 + arr2)
print(arr1 + 1)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]

![Screenshot 2023-03-28 at 4.21.56 PM.png]()

In [ ]:
# 경우2: 하나의 배열이 1차원인 경우
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
arr2 = np.array([1, 2, 3])
print(arr1 + arr2)
print(arr1 + [1, 2, 3])

[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]

![Screenshot 2023-03-28 at 4.27.02 PM.png]()

In [ ]:
# 둘다 1차원인데, 행과 열의 개수가 반대인 경우
arr1 = np.array([0, 1, 2]).reshape(3, 1)
arr2 = np.array([1, 2, 3])
print(arr1 + arr2)

[[1 2 3]
 [2 3 4]
 [3 4 5]]

### 2) Numpy 집계함수 사용

In [ ]:
# 1부터 10까지 연속적인 수로 이루어진 'a'라는 배열
# shape: 2X5인 2차원 배열
a = np.arange(1, 11).reshape(2, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

In [ ]:
# a 배열 속 원소들의 합
print(np.sum(a))

55

In [ ]:
 # a 배열의 열(column)별 원소들의 합
print(np.sum(a, axis = 0))

[ 7  9 11 13 15]

In [ ]:
# a 배열의 행(row)별 원소들의 합
print(np.sum(a, axis = 1))

[15 40]

In [ ]:
# a 배열 속 원소들의 평균
print(np.mean(a))

5.5

In [ ]:
# a 배열 속 원소들의 표준편차(standard deviation)
print(np.std(a))

2.8722813232690143

In [ ]:
# a 배열 속 원소들의 분산(variance)
print(np.var(a))

8.25

In [ ]:
# a 배열 속 원소들 중 최솟값
print(np.min(a))

# a 배열 속 원소들 중 최솟값의 인덱스(위치)
print(np.argmin(a))

1
0

In [ ]:
# a 배열 속 원소들 중 최댓값
print(np.max(a))

# a 배열 속 원소들 중 최댓값의 인덱스(위치)
print(np.argmax(a))

10
9

## **4. 인덱싱과 슬라이싱**

- 인덱스: 여러 원소를 가지고 있는 객체(리스트, 튜플, 배열 등)에 부여되는 번호
- 슬라이싱: 여러 원소를 가지고 있는 객체의 일부를 추출하는 것


---


- 파이썬의 List와 동일하게 ndarray도 인덱싱과 슬라이싱 사용 가능

### 1) Indexing (인덱싱)

In [ ]:
# 1부터 10까지 수 중 랜덤하게 6개의 수가 추출된 'arr1'이라는 배열
# shape: 3X2인 2차원 배열
arr1 = np.random.randint(1, 11, size = (3, 2))
print(arr1)

[[ 6  5]
 [ 3  5]
 [ 2 10]]

In [ ]:
# 1행 출력
print(arr1[0, :])

[6 5]

In [ ]:
# 2행 1열의 원소 출력
print(arr1[1, 0])

3

### 2) Slicing (슬라이싱)

- 1차원 배열의 슬라이싱

In [ ]:
# 10부터 19까지 연속적인 수로 이루어진 'arr2'라는 배열
# shape: 1차원 배열
arr2 = np.arange(10, 20)
print(arr2)

[10 11 12 13 14 15 16 17 18 19]

In [ ]:
# index가 4부터 6까지인 원소 출력
print(arr2[4:7])

[14 15 16]

In [ ]:
# index가 6 이상인 원소 출력
print(arr2[6:])

[16 17 18 19]

In [ ]:
# index가 6 이상인 원소를 모두 20으로 바꾸기
arr2[6:] = 20
print(arr2)

[10 11 12 13 14 15 20 20 20 20]

- 다차원 배열의 슬라이싱

In [ ]:
# 1부터 9까지 연속적인 수로 이루어진 'arr3'라는 배열
# shape: 3X3인 2차원 배열
arr3 = np.arange(1, 10).reshape(3, 3)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
# 2, 3, 5, 6으로 구성된 2차원 배열 출력
print(arr3[:2, 1:])

[[2 3]
 [5 6]]

In [ ]:
# 1행과 2행 출력
print(arr3[0])
print(arr3[0, :])

print(arr3[1])
print(arr3[1, :])

[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]

In [ ]:
# 2열 출력
print(arr3[:, 1])

[2 5 8]

In [ ]:
# 2, 3, 5, 6을 모두 결측치로 바꾸기
# 결측치: 데이터에 값이 없는 것 (NaN, null, None)
arr3[:2, 1:] = np.nan
print(arr3)

ValueError: cannot convert float NaN to integer

In [ ]:
# numpy에서 자료형이 float일 때만 결측치 삽입 가능
arr3 = arr3.astype(float)
arr3[:2, 1:] = np.nan
print(arr3)

[[ 1. nan nan]
 [ 4. nan nan]
 [ 7.  8.  9.]]

### 3) 마스킹 연산 (boolean 인덱싱)

- 마스킹 연산: 조건에 부합하는 데이터만 추출하는 방법

In [ ]:
# 난수가 표준정규분포 따르는 'arr4'라는 배열 생성
# shape: 5X5인 2차원 배열
arr4 = np.random.randn(5, 5)
print(arr4)

[[-0.37453987 -0.57102635 -0.53200159  0.61376061  0.6319637 ]
 [-0.21980583  0.85195765  1.65313949  0.76990233  0.42705562]
 [-1.1213026  -0.69117802 -2.24216541 -0.30863481  1.14862901]
 [-0.76091378 -1.69469221 -1.71006348 -0.56764386  0.28950432]
 [ 0.44640133 -1.2550299  -0.41459357 -0.02483118 -2.57713942]]

In [ ]:
# arr4 안의 원소가 양수이면 True, 음수이면 False 출력
print(arr4 > 0)

[[False False False  True  True]
 [False  True  True  True  True]
 [False False False False  True]
 [False False False False  True]
 [ True False False False False]]

In [ ]:
# arr4 안의 원소가 음수면 0 삽입
arr4 = np.where(arr4 > 0, arr4, 0) # 0은 broadcasting 되었다.
print(arr4)

[[0.         0.         0.         0.61376061 0.6319637 ]
 [0.         0.85195765 1.65313949 0.76990233 0.42705562]
 [0.         0.         0.         0.         1.14862901]
 [0.         0.         0.         0.         0.28950432]
 [0.44640133 0.         0.         0.         0.        ]]

# **Pandas**

In [ ]:
# 라이브러리 불러오기
import pandas as pd

## **1. Series**

### 1) Series 객체 생성

```
pd.Series(data, index = )
```

![series_피카츄.png]()

In [ ]:
# [방법1] list 사용
# 객체 이름: obj
obj = pd.Series(['피카츄', '전기', 35, 55, 40],
                index = ['이름', '속성', 'HP', '공격', '방어'])
print(obj)

이름    피카츄
속성     전기
HP     35
공격     55
방어     40
dtype: object

In [ ]:
# [방법2] tuple 사용
# 데이터 값 : 'value' 변수에 저장
# index 값 : 'index_name' 변수에 저장
# 객체 이름: obj
value = ('피카츄', '전기', 35, 55, 40)
index_name = ['이름', '속성', 'HP', '공격', '방어']
obj = pd.Series(value, index = index_name)
print(obj)

이름    피카츄
속성     전기
HP     35
공격     55
방어     40
dtype: object

In [ ]:
# [방법3] Dictionary 사용
# 객체 이름: obj
value = {'이름': '피카츄', '속성': '전기', 'HP': 35, '공격': 55, '방어': 40}
obj = pd.Series(value)
print(obj)

이름    피카츄
속성     전기
HP     35
공격     55
방어     40
dtype: object

### 2) Series 속성 확인

In [ ]:
# obj 객체의 index 확인
print(obj.index)

Index(['이름', '속성', 'HP', '공격', '방어'], dtype='object')

In [ ]:
# obj 객체의 데이터 값(value) 확인
print(obj.values)

['피카츄' '전기' 35 55 40]

In [ ]:
# obj 객체의 결측치 확인
# 결측치인 값: True 출력, 결측치가 아닌 값: False 출력
print(obj.isnull())

이름    False
속성    False
HP    False
공격    False
방어    False
dtype: bool

In [ ]:
# obj 객체의 결측치 확인
# 결측치인 값: False 출력, 결측치가 아닌 값: True 출력
print(obj.notnull())

이름    True
속성    True
HP    True
공격    True
방어    True
dtype: bool

### 3) Series 데이터 선택

![series_피카츄.png]()

- 피카츄의 속성은 무엇일까? (인덱싱)

In [ ]:
# [방법1] index 이름 사용
print(obj['속성'])

전기

In [ ]:
# [방법2] loc 사용
print(obj.loc['속성'])

전기

In [ ]:
# [방법3] iloc 사용
print(obj.iloc[1])

전기

- 피카츄의 HP, 공격, 방어 수치는? (슬라이싱)

In [ ]:
# [방법1] index 이름 사용
print(obj[['HP', '공격', '방어']])

HP    35
공격    55
방어    40
dtype: object

In [ ]:
# [방법2] loc 사용
# index 이름 'HP'부터 '방어'까지 출력
print(obj.loc['HP':'방어'])

HP    35
공격    55
방어    40
dtype: object

In [ ]:
# [방법3] iloc 사용
# index 번호 2부터 4까지 출력
print(obj.iloc[2:5])

HP    35
공격    55
방어    40
dtype: object

### 4) Series 데이터 연산

- 단일 Series내 연산

In [ ]:
# 피카츄의 HP가 2배 증가
# 데이터 선택 방법: loc을 사용한 인덱싱
obj['HP'] = obj.loc['HP'] * 2
print(obj)

이름    피카츄
속성     전기
HP     70
공격     55
방어     40
dtype: object

In [ ]:
# 피카츄의 공격력과 방어력이 2배 감소
# 데이터 선택 방법: iloc을 사용한 슬라이싱
# 공격(3), 방어(4)
obj.iloc[3:5] = obj.iloc[3:5] / 2
print(obj)

이름     피카츄
속성      전기
HP      70
공격    27.5
방어    20.0
dtype: object

In [ ]:
# HP, 공격, 방어 총합 계산
# 데이터 선택 방법: loc을 사용한 슬라이싱
# 집계함수 활용
print(obj.loc['HP':'방어'].sum())

117.5

In [ ]:
# HP(2), 공격, 방어(4) 평균 계산
# 데이터 선택 방법: iloc을 사용한 슬라이싱
# 집계함수 활용
print(obj.iloc[2:5].mean())

39.166666666666664

- 2개의 Series간 연산

![chlwhd,,.png]()

In [ ]:
# 위와 같은 2개의 obj1, obj2 series 객체 생성 (결측치는 np.nan 삽입)
# obj1은 list를 사용해 series 생성
obj1 = pd.Series(['피카츄', 35, 55, 40, np.nan], index = ['이름', 'HP', '공격', '방어', '스피드'])
# obj2는 dictionary를 사용해 series 생성
obj2 = pd.Series({'이름': '파이리', 'HP': 39, '공격': 52, '방어': np.nan, '스피드': 65})

print(obj1)
print(obj2)

이름     피카츄
HP      35
공격      55
방어      40
스피드    NaN
dtype: object
이름     파이리
HP      39
공격      52
방어     NaN
스피드     65
dtype: object

In [ ]:
# obj1 객체의 수치 부분만 obj1_num 변수에 저장 (loc사용)
# obj2 객체의 수치 부분만 obj2_num 변수에 저장 (iloc 사용)
obj1_num = obj1.loc['HP':'스피드']
obj2_num = obj2.iloc[1:]

print(obj1_num)
print(obj2_num)

HP      35
공격      55
방어      40
스피드    NaN
dtype: object
HP      39
공격      52
방어     NaN
스피드     65
dtype: object

In [ ]:
# obj1_num과 obj2_num 덧셈
# 더하기 기호 사용
print(obj1_num + obj2_num)

HP      74
공격     107
방어     NaN
스피드    NaN
dtype: object

In [ ]:
# obj1_num과 obj2_num 덧셈
# .add 함수 사용
print(obj1_num.add(obj2_num))

HP      74
공격     107
방어     NaN
스피드    NaN
dtype: object

In [ ]:
# obj1_num과 obj2_num 덧셈
# 결측치 30으로 채우기
obj1_num.add(obj2_num, fill_value = 30)

HP      74
공격     107
방어      70
스피드     95
dtype: object

## **2. Data Frame**

### 0) csv 파일 불러오기

In [ ]:
# 실습 데이터가 구글 Drive에 있는 경우, gdrive와 연동해야 함
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/

In [ ]:
# pokemon.csv 파일 읽어와서 'df' 변수에 저장
# gdrive에 파일 저장하고, 파일경로는 경로복사 기능을 통해서 경로복사 하기

import pandas as pd
df = pd.read_csv("/content/gdrive/MyDrive/Classroom/[데이터반 B] 2024 제 3회  OUTTA 부트캠프/pokemon.csv")

### 1) DataFrame 속성 확인

In [ ]:
# DataFrame 정보(행과 열의 개수, 결측치, 데이터타입 등) 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  800 non-null    int64
 1   #           800 non-null    int64
 2   Name        800 non-null    object
 3   Type 1      800 non-null    object
 4   Type 2      414 non-null    object
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [ ]:
# DataFrame의 column 확인
print(df.columns)

Index(['Unnamed: 0', '#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack',
       'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
# DataFrame의 index 확인
print(df.index)

RangeIndex(start=0, stop=800, step=1)

In [ ]:
# DataFrame 속 데이터 상단 5개의 행 출력
df.head(5)

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
# DataFrame 속 데이터 하단 7개의 행 출력
df.tail(7)

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
793,793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- 결측치 확인 및 처리

```
# 결측치 확인
df.isnull()
df.isna()

df.notnull()
df.notna()

# 결측치 처리
df.fillna('결측치 채울 값')
df.dropna()
```

In [ ]:
# column별 결측치 수 확인
df.isnull().sum()

Unnamed: 0      0
#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
# 결측치 'Normal'로 채우기
df.fillna('Normal')

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,Normal,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
# 결측치 포함하고 있는 행 삭제
df.dropna()

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
6,6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### 2) DataFrame 데이터 선택

- 행(row) 선택

```
# loc 사용
df.loc['row 이름']
# iloc 사용
df.iloc[row 번호]
```

In [ ]:
# 'Name'열을 index로 지정
df.set_index('Name', inplace = True)

In [ ]:
# 피카츄(Pikachu)행 선택
# loc 사용
df.loc['Pikachu']

Unnamed: 0          30
#                   25
Type 1        Electric
Type 2             NaN
HP                  35
Attack              55
Defense             40
Sp. Atk             50
Sp. Def             50
Speed               90
Generation           1
Legendary        False
Name: Pikachu, dtype: object

In [ ]:
# 피카츄(Pikachu)와 라이츄(Raichu)행 선택
# loc 사용
# 2개 이상 행 선택 시, 대괄호 2개 필요!
df.loc[['Pikachu', 'Raichu']]

,Unnamed: 0,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Pikachu,30,25,Electric,NaN,35,55,40,50,50,90,1,False
Raichu,31,26,Electric,NaN,60,90,55,90,80,110,1,False

- 열(column) 선택


```
df['column명']
```

In [ ]:
# Speed열 선택
df['Speed']

Name
Bulbasaur                 45
Ivysaur                   60
Venusaur                  80
VenusaurMega Venusaur     80
Charmander                65
                        ...
Diancie                   50
DiancieMega Diancie      110
HoopaHoopa Confined       70
HoopaHoopa Unbound        80
Volcanion                 70
Name: Speed, Length: 800, dtype: int64

In [ ]:
# 포켓몬들의 Speed 평균값
df['Speed'].mean()

68.2775

In [ ]:
# 포켓몬들의 Speed 중앙값
df['Speed'].median()

65.0

In [ ]:
# 'Type 1'열 선택
df['Type 1']

Name
Bulbasaur                  Grass
Ivysaur                    Grass
Venusaur                   Grass
VenusaurMega Venusaur      Grass
Charmander                  Fire
                          ...
Diancie                     Rock
DiancieMega Diancie         Rock
HoopaHoopa Confined      Psychic
HoopaHoopa Unbound       Psychic
Volcanion                   Fire
Name: Type 1, Length: 800, dtype: object

In [ ]:
# Type1이 Water인 데이터 선택 (데이터 필터링)
df[df['Type 1'] == 'Water']

,Unnamed: 0,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Squirtle,9,7,Water,NaN,44,48,65,50,64,43,1,False
Wartortle,10,8,Water,NaN,59,63,80,65,80,58,1,False
Blastoise,11,9,Water,NaN,79,83,100,85,105,78,1,False
BlastoiseMega Blastoise,12,9,Water,NaN,79,103,120,135,115,78,1,False
Psyduck,59,54,Water,NaN,50,52,48,65,50,55,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Froakie,724,656,Water,NaN,41,56,40,62,44,71,6,False
Frogadier,725,657,Water,NaN,54,63,52,83,56,97,6,False
Greninja,726,658,Water,Dark,72,95,67,103,71,122,6,False
Clauncher,762,692,Water,NaN,50,53,62,58,63,44,6,False
Clawitzer,763,693,Water,NaN,71,73,88,120,89,59,6,False

In [ ]:
# HP가 50 이상인 데이터 선택 (데이터 필터링)
df[df['HP'] >= 50]

,Unnamed: 0,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Ivysaur,1,2,Grass,Poison,60,62,63,80,80,60,1,False
Venusaur,2,3,Grass,Poison,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,3,Grass,Poison,80,100,123,122,120,80,1,False
Charmeleon,5,5,Fire,NaN,58,64,58,80,65,80,1,False
Charizard,6,6,Fire,Flying,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,795,719,Rock,Fairy,50,100,150,100,150,50,6,True
DiancieMega Diancie,796,719,Rock,Fairy,50,160,110,160,110,110,6,True
HoopaHoopa Confined,797,720,Psychic,Ghost,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,798,720,Psychic,Dark,80,160,60,170,130,80,6,True
Volcanion,799,721,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
# Type1이 Water이고, HP가 50 이상인 데이터 선택 (데이터 필터링)
df[(df['Type 1'] == 'Water') & (df['HP'] >= 50)]

,Unnamed: 0,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Wartortle,10,8,Water,NaN,59,63,80,65,80,58,1,False
Blastoise,11,9,Water,NaN,79,83,100,85,105,78,1,False
BlastoiseMega Blastoise,12,9,Water,NaN,79,103,120,135,115,78,1,False
Psyduck,59,54,Water,NaN,50,52,48,65,50,55,1,False
Golduck,60,55,Water,NaN,80,82,78,95,80,85,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
KeldeoResolute Forme,714,647,Water,Fighting,91,72,90,129,90,108,5,False
Frogadier,725,657,Water,NaN,54,63,52,83,56,97,6,False
Greninja,726,658,Water,Dark,72,95,67,103,71,122,6,False
Clauncher,762,692,Water,NaN,50,53,62,58,63,44,6,False
Clawitzer,763,693,Water,NaN,71,73,88,120,89,59,6,False

- 행과 열 선택
```
# loc 사용 (행 먼저)
df.loc['행 이름', '열 이름']
# iloc 사용 (행 먼저)
df.iloc[행 번호, 열 번호]
# column명 사용 (열 먼저)
df['열 이름'][행 번호]
```

In [ ]:
# 모든 포켓몬들의 Type 1, Type 2만 선택
# loc 사용
df.loc[:, ['Type 1', 'Type 2']]

                        Type 1  Type 2
Name
Bulbasaur                Grass  Poison
Ivysaur                  Grass  Poison
Venusaur                 Grass  Poison
VenusaurMega Venusaur    Grass  Poison
Charmander                Fire     NaN
...                        ...     ...
Diancie                   Rock   Fairy
DiancieMega Diancie       Rock   Fairy
HoopaHoopa Confined    Psychic   Ghost
HoopaHoopa Unbound     Psychic    Dark
Volcanion                 Fire   Water

[800 rows x 2 columns]

In [ ]:
# index번호가 2부터 10까지인 포켓몬들의 HP(4) 선택
# iloc 사용
df.iloc[2:11, 4]

Name
Venusaur                     80
VenusaurMega Venusaur        80
Charmander                   39
Charmeleon                   58
Charizard                    78
CharizardMega Charizard X    78
CharizardMega Charizard Y    78
Squirtle                     44
Wartortle                    59
Name: HP, dtype: int64

In [ ]:
# 처음 10개 포켓몬들의 HP(4)부터 speed(9) 데이터 선택
# iloc 사용
df.iloc[:10, 4:10]

                           HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
Name
Bulbasaur                  45      49       49       65       65     45
Ivysaur                    60      62       63       80       80     60
Venusaur                   80      82       83      100      100     80
VenusaurMega Venusaur      80     100      123      122      120     80
Charmander                 39      52       43       60       50     65
Charmeleon                 58      64       58       80       65     80
Charizard                  78      84       78      109       85    100
CharizardMega Charizard X  78     130      111      130       85    100
CharizardMega Charizard Y  78     104       78      159      115    100
Squirtle                   44      48       65       50       64     43

### 3) DataFrame 데이터 수정

- 행/열 추가 및 삭제

```
# 행 추가
df.loc['새로운 행 이름'] = 데이터 값
# 열 추가
df['새로운 열 이름'] = 데이터 값
```


```
# 행 삭제
df.drop(행 이름, axis = 0)
# 열 삭제
df.drop(열 이름, axis = 1)
```

In [ ]:
# 'Unnamed: 0'column 삭제
# 원본 df에 수정사항 저장

df.drop('Unnamed: 0', axis = 1, inplace = True)

In [ ]:
# HP, Attack, Defense, Sp. Atk, Sp. Def, Speed 모두 더하여
# 'Total' 이름의 column 추가
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,False,318
Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,False,405
Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,False,525
VenusaurMega Venusaur,3,Grass,Poison,80,100,123,122,120,80,1,False,625
Charmander,4,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,50,100,150,100,150,50,6,True,600
DiancieMega Diancie,719,Rock,Fairy,50,160,110,160,110,110,6,True,700
HoopaHoopa Confined,720,Psychic,Ghost,80,110,60,150,130,70,6,True,600
HoopaHoopa Unbound,720,Psychic,Dark,80,160,60,170,130,80,6,True,680
Volcanion,721,Fire,Water,80,110,120,130,90,70,6,True,600

In [ ]:
# 위의 과정을 .sum() 함수 이용하여 시행
# 데이터 선택 방법: iloc을 사용한 슬라이싱
df['Total'] = df.iloc[:, 4:10].sum(axis = 1)
df

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,False,274
Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,False,346
Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,False,446
VenusaurMega Venusaur,3,Grass,Poison,80,100,123,122,120,80,1,False,546
Charmander,4,Fire,NaN,39,52,43,60,50,65,1,False,271
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,50,100,150,100,150,50,6,True,556
DiancieMega Diancie,719,Rock,Fairy,50,160,110,160,110,110,6,True,656
HoopaHoopa Confined,720,Psychic,Ghost,80,110,60,150,130,70,6,True,526
HoopaHoopa Unbound,720,Psychic,Dark,80,160,60,170,130,80,6,True,606
Volcanion,721,Fire,Water,80,110,120,130,90,70,6,True,526

- 특정 데이터값 다른 값으로 대체 (replace 함수)

In [ ]:
# 목표: Legendary 포켓몬 개수 세기

In [ ]:
# 1단계) Legendary column에서 True는 1로, False는 0으로 바꾸기
# 원본 df에 수정사항 저장
df['Legendary'] = df['Legendary'].replace({True: 1, False: 0})
df

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,0,274
Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,0,346
Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,0,446
VenusaurMega Venusaur,3,Grass,Poison,80,100,123,122,120,80,1,0,546
Charmander,4,Fire,NaN,39,52,43,60,50,65,1,0,271
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,50,100,150,100,150,50,6,1,556
DiancieMega Diancie,719,Rock,Fairy,50,160,110,160,110,110,6,1,656
HoopaHoopa Confined,720,Psychic,Ghost,80,110,60,150,130,70,6,1,526
HoopaHoopa Unbound,720,Psychic,Dark,80,160,60,170,130,80,6,1,606
Volcanion,721,Fire,Water,80,110,120,130,90,70,6,1,526

In [ ]:
# 2단계) Legendary column 세로로 더하기
df['Legendary'].sum(axis = 0)

65

- 데이터 정렬


```
# index 기준 정렬
df.sort_index(ascending = T/F)

# value 기준 정렬
df.sort_values(기준 열, ascending = T/F)
```

In [ ]:
# 포켓몬 이름 알파벳 순서로 정렬
df.sort_values('Name', ascending = True)

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
Abomasnow,460,Grass,Ice,90,92,75,92,85,60,4,0,408
AbomasnowMega Abomasnow,460,Grass,Ice,90,132,105,132,105,30,4,0,508
Abra,63,Psychic,NaN,25,20,15,105,55,90,1,0,286
Absol,359,Dark,NaN,65,130,60,75,60,75,3,0,403
AbsolMega Absol,359,Dark,NaN,65,150,60,115,60,115,3,0,503
...,...,...,...,...,...,...,...,...,...,...,...,...
Zoroark,571,Dark,NaN,60,105,60,120,60,105,5,0,455
Zorua,570,Dark,NaN,40,65,40,80,40,65,5,0,295
Zubat,41,Poison,Flying,40,45,35,30,40,55,1,0,206
Zweilous,634,Dark,Dragon,72,85,70,65,70,58,5,0,353
Zygarde50% Forme,718,Dragon,Ground,108,100,121,81,95,95,6,1,498

In [ ]:
# Attack 높은 순서로 정렬
df.sort_values('Attack', ascending = False)

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
MewtwoMega Mewtwo X,150,Psychic,Fighting,106,190,100,154,100,130,1,1,675
HeracrossMega Heracross,214,Bug,Fighting,80,185,115,40,105,75,2,0,522
GroudonPrimal Groudon,383,Ground,Fire,100,180,160,150,90,90,3,1,673
RayquazaMega Rayquaza,384,Dragon,Flying,105,180,100,180,100,115,3,1,678
DeoxysAttack Forme,386,Psychic,NaN,50,180,20,180,20,150,3,1,553
...,...,...,...,...,...,...,...,...,...,...,...,...
Magikarp,129,Water,NaN,20,10,55,15,20,80,1,0,181
Blissey,242,Normal,NaN,255,10,10,75,135,55,2,0,287
Shuckle,213,Bug,Rock,20,10,230,10,230,5,2,0,487
Chansey,113,Normal,NaN,250,5,5,35,105,50,1,0,201
Happiny,440,Normal,NaN,100,5,5,15,65,30,4,0,124

In [ ]:
# 동일한 Type 1끼리 정렬
df.sort_values('Type 1')

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
Sewaddle,540,Bug,Grass,45,53,70,40,60,42,5,0,270
Pinsir,127,Bug,NaN,65,125,100,55,70,85,1,0,436
Burmy,412,Bug,NaN,40,29,45,29,45,36,4,0,188
Scyther,123,Bug,Flying,70,110,80,55,80,105,1,0,431
Joltik,595,Bug,Electric,50,47,50,57,50,65,5,0,274
...,...,...,...,...,...,...,...,...,...,...,...,...
Totodile,158,Water,NaN,50,65,64,44,48,43,2,0,266
Basculin,550,Water,NaN,70,92,65,80,55,98,5,0,395
Vaporeon,134,Water,NaN,130,65,60,110,95,65,1,0,396
Panpour,515,Water,NaN,50,53,48,53,48,64,5,0,271
Chinchou,170,Water,Electric,75,38,38,56,56,67,2,0,257

In [ ]:
# 동일한 Type 1끼리 정렬, 동일한 Type 1내에서는 HP 오름차순으로 정렬
df.sort_values(['Type 1', 'HP'])

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
Shedinja,292,Bug,Ghost,1,90,45,30,30,40,3,0,238
Shuckle,213,Bug,Rock,20,10,230,10,230,5,2,0,487
Combee,415,Bug,Flying,30,30,42,30,42,70,4,0,218
Venipede,543,Bug,Poison,30,45,59,30,39,57,5,0,235
Nincada,290,Bug,Ground,31,45,90,30,30,40,3,0,238
...,...,...,...,...,...,...,...,...,...,...,...,...
Lapras,131,Water,Ice,130,85,80,85,95,60,1,0,406
Vaporeon,134,Water,NaN,130,65,60,110,95,65,1,0,396
Wailmer,320,Water,NaN,130,70,35,70,35,60,3,0,273
Alomomola,594,Water,NaN,165,75,80,40,45,65,5,0,310
Wailord,321,Water,NaN,170,90,45,90,45,60,3,0,333

### 4) DataFrame 데이터 연산

- 데이터 기술통계량 확인

In [ ]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000,800.00000,800.000000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375,0.08125,369.167500
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129,0.27339,106.157884
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000,0.00000,122.000000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000,0.00000,279.000000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000,0.00000,373.000000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000,0.00000,436.000000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000,1.00000,678.000000

- 수치 데이터에 함수 적용 (apply 함수)

In [ ]:
# 목표: HP가 50미만인 포켓몬들에게 HP+20, Attack+20, Defense+20 하기
# HP가 50 미만인 포켓몬들의 HP, Attack, Defense를 각각 20씩 증가시키는 함수
def increase_stats(row):
    if row['HP'] < 50:
        row['HP'] += 20
        row['Attack'] += 20
        row['Defense'] += 20
    return row

# apply를 사용하여 함수 적용
df.apply(increase_stats, axis=1)

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,65,69,69,65,65,45,1,0,274
Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,0,346
Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,0,446
VenusaurMega Venusaur,3,Grass,Poison,80,100,123,122,120,80,1,0,546
Charmander,4,Fire,NaN,59,72,63,60,50,65,1,0,271
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,50,100,150,100,150,50,6,1,556
DiancieMega Diancie,719,Rock,Fairy,50,160,110,160,110,110,6,1,656
HoopaHoopa Confined,720,Psychic,Ghost,80,110,60,150,130,70,6,1,526
HoopaHoopa Unbound,720,Psychic,Dark,80,160,60,170,130,80,6,1,606
Volcanion,721,Fire,Water,80,110,120,130,90,70,6,1,526

- 데이터 그룹화 (groupby 함수)

In [ ]:
# Type 1을 기준으로 데이터 그룹화, 그룹별 데이터 개수 확인
df.groupby('Type 1').count()

,#,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,,
Bug,69,52,69,69,69,69,69,69,69,69,69
Dark,31,21,31,31,31,31,31,31,31,31,31
Dragon,32,21,32,32,32,32,32,32,32,32,32
Electric,44,17,44,44,44,44,44,44,44,44,44
Fairy,17,2,17,17,17,17,17,17,17,17,17
Fighting,27,7,27,27,27,27,27,27,27,27,27
Fire,52,24,52,52,52,52,52,52,52,52,52
Flying,4,2,4,4,4,4,4,4,4,4,4
Ghost,32,22,32,32,32,32,32,32,32,32,32
Grass,70,37,70,70,70,70,70,70,70,70,70
Ground,32,19,32,32,32,32,32,32,32,32,32
Ice,24,11,24,24,24,24,24,24,24,24,24
Normal,98,37,98,98,98,98,98,98,98,98,98
Poison,28,13,28,28,28,28,28,28,28,28,28
Psychic,57,19,57,57,57,57,57,57,57,57,57
Rock,44,35,44,44,44,44,44,44,44,44,44
Steel,27,22,27,27,27,27,27,27,27,27,27
Water,112,53,112,112,112,112,112,112,112,112,112

In [ ]:
# Type 1을 기준으로 데이터 그룹화, 그룹별 데이터 값의 합 확인
df.groupby('Type 1').sum()

,#,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,,
Bug,23080,FlyingPoisonPoisonPoisonPoisonGrassGrassPoison...,3925,4897,4880,3717,4471,4256,222,0,22443
Dark,14302,FlyingIceFireFireFireGhostGhostFlyingIceFighti...,2071,2740,2177,2314,2155,2361,125,2,11872
Dragon,15180,FlyingFlyingFairyFlyingFlyingPsychicPsychicPsy...,2666,3588,2764,3099,2843,2657,124,12,15075
Electric,15994,SteelSteelFlyingDragonSteelGhostFireWaterIceFl...,2631,3040,2917,3961,3243,3718,144,4,17023
Fairy,7642,FlyingFlying,1260,1046,1117,1335,1440,826,70,1,5834
Fighting,9824,PsychicPsychicPsychicSteelSteelDarkFlying,1886,2613,1780,1434,1747,1784,91,0,9449
Fire,17025,FlyingDragonFlyingFlyingRockFlyingFightingFigh...,3635,4408,3524,4627,3755,3871,167,5,20352
Flying,2711,DragonDragon,283,315,265,377,290,410,22,2,1679
Ghost,15568,PoisonPoisonPoisonPoisonFlyingFlyingDarkDragon...,2062,2361,2598,2539,2447,2059,134,2,12138
Grass,24141,PoisonPoisonPoisonPoisonPoisonPoisonPoisonPois...,4709,5125,4956,5425,4930,4335,235,3,25006
Ground,11401,RockRockFlyingDragonDragonPsychicPsychicFireRo...,2361,3064,2715,1807,2008,2045,101,4,11740
Ice,10165,PsychicFlyingGroundGroundFlyingPsychicWaterWat...,1728,1746,1714,1861,1831,1523,85,2,8760
Normal,31279,FlyingFlyingFlyingFlyingFlyingFlyingFairyFairy...,7573,7200,5865,5470,6245,7012,299,2,32091
Poison,7050,GroundGroundFlyingFlyingFlyingDarkDarkBugDarkF...,1883,2091,1927,1692,1803,1780,71,0,9364
Psychic,21706,FairyFightingFlyingFlyingFlyingGrassFairyFairy...,4026,4073,3858,5609,4918,4645,193,14,23296
Rock,17280,GroundGroundGroundGroundWaterWaterWaterWaterFl...,2876,4086,4435,2787,3321,2460,152,4,17241
Steel,11957,GroundGroundFlyingFairyFairyRockRockRockPsychi...,1761,2503,3412,1823,2177,1492,104,4,11511
Water,33946,FightingPoisonPoisonPsychicPsychicPsychicIceIc...,8071,8305,8170,8379,7898,7388,320,4,40460

### 5) csv 파일로 저장

- 파일 저장하기

```
df.to_csv('파일경로/파일이름.csv')
```

In [ ]:
# df 객체를 'pokemon_analysis.csv'로 저장
df.to_csv('pokemon_analysis.csv', index = False)

# **과제**

## **타이타닉 데이터셋**

In [ ]:
# 실습 과제에서 사용할 titanic 데이터셋을 불러오는 코드입니다.
# 실습 진행 전 꼭 실행해주세요.
import seaborn as sns
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# pandas 라이브러리 불러와주세요. (5점)
import pandas as pd

### [목표1] Dataframe의 속성을 확인해봅시다. (10점)

In [ ]:
# 'df' 객체의 column 이름을 확인해주세요. (5점)
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
# 'df' 객체의 상단 5개 행을 출력해주세요. (5점)
df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### [목표2] Dataframe의 결측치를 확인하고, 상황에 맞게 결측치를 처리해봅시다. (35점)

- 결측치 확인 (10점)

In [ ]:
# df 객체의 column별 결측치 수를 확인해주세요. (10점)
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

- 결측치 처리 (25점)

In [ ]:
# 결측치가 많은 'deck'열을 삭제해주세요. (10점)
# inplace 옵션을 지정해 원본 df에 수정사항을 반영해주세요.
df.drop('deck',axis=1,inplace=True)

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [ ]:
# 'age'열은 'age'열의 평균으로 결측치를 채워주세요. (15점)
# inplace 옵션을 지정해 원본 df에 수정사항을 반영해주세요.
# 목표를 수행할 수 있는 코드를 스스로 작성해보시고, 도움이 필요하시면 아래 단계를 차근차근 따라서 실습해주세요.
'''
1단계: 'age'열을 선택해주세요.
2단계: 위에서 선택한 'age'열에 결측치를 채우는 함수를 덧붙여주세요.
3단계: 함수 안에 채울 값('age'열의 평균 구하는 코드)을 넣어주세요.
4단계: 함수 안에 inplace 옵션을 지정해주세요.
'''

df['age'].fillna(df['age'].mean(),inplace=True)

In [ ]:
# 이 코드를 실행하여 위에서 결측치를 처리한 것이 어떻게 df 데이터프레임에 반영되었는지 확인해주세요.
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [ ]:
df.isnull().sum() # age 결측값 없음 확인

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

### [목표3] 1등석, 2등석, 3등석 각각의 평균 운임을 확인해봅시다. (15점)

In [ ]:
# 목표를 수행할 수 있는 코드를 스스로 작성해보시고, 도움이 필요하시면 아래 단계를 차근차근 따라서 실습해주세요.
'''
1단계. 좌석 정보가 담긴 'class'열을 기준으로 데이터를 묶어주세요.
2단계. 위의 결과에서 운임 정보가 담긴 'fare'열을 선택해주세요.
3단계. 위의 결과에 평균을 구하는 함수를 덧붙여주세요.
'''

df.groupby('class')['fare'].mean()

class
First     84.154687
Second    20.662183
Third     13.675550
Name: fare, dtype: float64

### [목표4] Southampton에 정박한 5세 이하 아이들의 운임을 3만큼 빼주는 코드를 작성해봅시다. (30점)

(1) Southampton에 정박한 5세 이하 아이들의 운임 데이터를 선택하여 's_child' 변수에 저장해주세요. (15점)

In [ ]:
# 목표를 수행할 수 있는 코드를 스스로 작성해보시고, 도움이 필요하시면 아래 단계를 차근차근 따라서 실습해주세요.
'''
1단계. 'embark_town'이 'Southampton'인지 확인하는 코드를 작성해주세요.
2단계. 'age'가 5 이하인지 확인하는 코드를 작성해주세요.
3단계. 위의 코드를 df[ ]안에 넣어서 두 조건을 모두 만족하는 데이터를 선택해주세요.
4단계. 위에서 선택한 데이터 중 'fare'열만 선택해주세요.
5단계. 선택된 데이터를 s_child 변수에 저장해주세요.
'''

data = df['embark_town']=='Southampton'
age = df['age']<=5
s_child = df[data & age]['fare']

In [ ]:
# 이 코드를 실행하여 s_child가 잘 만들어졌는지 확인해주세요.
print(s_child)

7       21.0750
10      16.7000
58      27.7500
63      27.9000
78      29.0000
119     31.2750
164     39.6875
172     11.1333
183     39.0000
184     22.0250
193     26.0000
205     10.4625
233     31.3875
261     31.3875
297    151.5500
305    151.5500
340     26.0000
348     15.9000
374     21.0750
386     46.9000
407     18.7500
445     81.8583
479     12.2875
530     26.0000
618     39.0000
642     27.9000
750     23.0000
755     14.5000
777     12.4750
788     20.5750
824     39.6875
831     18.7500
850     31.2750
869     11.1333
Name: fare, dtype: float64

(2) lambda를 사용하여 x - 3을 해주는 함수 f를 만들고, s_child 데이터에 적용해주세요. (15점)

In [ ]:
f = lambda x : x -3
s_child.apply(f)

7       18.0750
10      13.7000
58      24.7500
63      24.9000
78      26.0000
119     28.2750
164     36.6875
172      8.1333
183     36.0000
184     19.0250
193     23.0000
205      7.4625
233     28.3875
261     28.3875
297    148.5500
305    148.5500
340     23.0000
348     12.9000
374     18.0750
386     43.9000
407     15.7500
445     78.8583
479      9.2875
530     23.0000
618     36.0000
642     24.9000
750     20.0000
755     11.5000
777      9.4750
788     17.5750
824     36.6875
831     15.7500
850     28.2750
869      8.1333
Name: fare, dtype: float64

### [목표5] Dataframe을 파일로 저장해봅시다. (5점)

In [ ]:
# df 객체를 'titanic_실습.csv'로 저장해주세요.
df.to_csv("/content/gdrive/MyDrive/Classroom/[데이터반 B] 2024 제 3회  OUTTA 부트캠프//titanic_실습.csv")